# Generated by Django 5.2 on 2026-08-07 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_card',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
