# Generated by Django 5.2 on 2026-08-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='properties/default.jpg', upload_to='properties/')),
                ('image2', models.ImageField(default='properties/default.jpg', upload_to='properties/')),
                ('image3', models.ImageField(default='properties/default.jpg', upload_to='properties/')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('video', models.TextField()),
                ('floor', models.ImageField(default='properties/default.jpg', upload_to='properties/')),
                ('map', models.TextField()),
                ('location', models.CharField()),
                ('beds', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('area', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root.agent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.property_type')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.status')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
